<?php
    /**
     * @see Laurent_OrderTickets_Block_Order_Tabs
     */
?>
<ul class="order-tabs">
    <li class="<?php if($this->pageIsOrderView()):?>active<?php endif; ?>">
        <a href="<?php echo $this->getOrderViewLink() ?>" class="link-cart">
                <?php echo $this->__('Details') ?>
        </a>
    </li>
    <li class="<?php if($this->pageIsOrderChat()):?>active<?php endif; ?>">
        <a href="<?php echo $this->getOrderChatLink() ?>" class="link-cart">
                <?php echo $this->__('Messages') ?>
        </a>
    </li>
</ul>