<?php
/**
 * @see Laurent_OrderTickets_Block_Adminhtml_Order_View_Tab_Tickets
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Order tickets'); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
    <?php if($this->hasChat()):?>
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><?php echo $this->__('Created at') ?></td>
                <td class="value"><?php echo Mage::helper('core')->formatDate($this->getChat()->getCreatedAt(), 'full', true)?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Last answer date') ?></td>
                <td class="value"><?php echo Mage::helper('core')->formatDate($this->getChat()->getLastAnswerDate(), 'full', true)?></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Status') ?></td>
                <td class="value"><?php echo $this->getChat()->getStatusLabel() ?></td>
            </tr>
            <tr>
                <td class="label">
                    <a href="<?php echo $this->getChatViewUrl()?>">
                        &gt; <?php echo $this->__('Details') ?>
                    </a>
                </td>
                <td class="value"></td>
            </tr>
        </table>
    <?php else: ?>
            <?php echo $this->__('There is no ticket associated to this order')?>
    <?php endif; ?>
    </div>
</div>
